name: FGO Login System

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # NA : 12:30PM GMT+8
    - cron: "30 04 * * *"
    # JP : 4:30AM GMT+8
    - cron: "30 20 * * *"
    # All : 5:00PM GMT+8
    - cron : "30 09 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Gettings files from Repo
        uses: actions/checkout@v3
        
      - name : Use Setup Python
        uses: actions/setup-python@v4
        
      - name: Install Requirements
        run: pip install -r https://raw.githubusercontent.com/FleetingComet/FGO-Daily-Login/master/requirements.txt --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org --upgrade pip

      - name: Execute main script
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
