name: "See secrets"

on: 
    push:
        branches: [master]
    workflow_dispatch:
        
jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_DEBUG: true
        envkey_SECRETS: ${{ toJSON(secrets) }}
        # envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        file_name: .env
        fail_on_empty: true

    - name: List files in current directory
      run: |
        echo "Current directory: $(pwd)"
        ls -la
    
    - name: Locate .env file
      run: |
        echo "Searching for .env file"
        find . -name ".env"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cats
        path: $(find . -name ".env" | head -n 1)
